name: TypeScript CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
            - name: npm install, build, and test
              run: |
                  yarn
                  yarn test
                  yarn build
              env:
                  CI: true
